export const INPUT_ON_CHANGE="INPUT_ON_CHANGE";
export const CALCULATE_ONCLICK="CALCULATE_ONCLICK"

export const LOGIN_REQ="LOGIN_REQ"
export const LOGIN_SUCESS="LOGIN_SUCESS"
export const LOGIN_FAIL="LOGIN_FAIL"

export const LOGOUT_REQ="LOGOUT_REQ"